### PR TITLE
Interactive tiles

### PR DESCRIPTION
**Pull request by joberthel**
So I had the problem, that the player can't really interact with the map itself (except for the scripting feature / popups). I thought about little things, like slightly moving grass if you walk through it.

https://user-images.githubusercontent.com/34104366/114229917-c5e24e00-9978-11eb-8c57-41e49ad68bfc.mp4

**How it works**: You basically create animated tiles in Tiled and add the boolean property "interactive" to the layer. The game will then play that animation, if you walk onto that tile.

mapProperties

Additionally you are able to add the int property "interactionRadius" which will trigger the animation before you walk onto the tile. If you are in the specified radius.

If you specified the interaction radius "-1", then it will trigger the animation of all tiles in that layer, if you walk onto one of them.

tileProperties

The tile has an optional property "reverseInactive". If this is set to true, then it will play the animation reversed, if you leave the tile. Otherwise it will just play the animation until it is finished.

https://user-images.githubusercontent.com/34104366/114230379-60429180-9979-11eb-8ba8-ef94097733d3.mp4

This feature also works with remote players, but not with companions. But that could easily be added.

I created an example map, so you can test the feature: /_/global/joberthel.github.io/workadventure-interactive-map/map.json

_____

If someone wants to merge this pull request into a fork with a newer phaser version, you will need to change the following line in the InteractiveLayer.ts, since the phaser api changed for this method (Line 158):

```
sprite.anims.play(entity.animation, false, sprite.anims.currentFrame.index);
// This line needs to be changed to the following if you update to the new phaser version 3.54.0
// sprite.anims.play({ key: entity.animation, startFrame: sprite.anims.currentFrame.index }, false);
```

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @joberthel ,

First of all, thanks a lot for the energy you are putting in this PR (and the last one about companions). Your code is clean, and the PR description is really complete!

To be completely honest, I'm a bit reluctant with merging this PR as it is now. I understand the need for adding interactions between the map and the player. But each new property we are adding to WorkAdventure is a property we need to maintain on the long run. And if we think about it, there are really countless properties we could add (to manage animations, doors, etc...)

Furthermore, we cannot really deprecate or modify the behaviour of a property (otherwise, we are going to break maps of other users). So when we add a new property, we need to be 100% sure about it.

So my idea was rather to push the scripting API forward so that this whole PR could be implemented from the scripting API.

What we would need for that is:

- A way to set Tiles from the scripting API (`WA.setTile()`) => some discussion was starter here: https://github.com/thecodingmachine/workadventure/issues/869
- A way to listen for all player positions (`WA.onUserMoves()`)
- A way to get the JSON from the map (to read the properties) `WA.getMap()` ?

If we have this, we can reimplement your PR, but in an external script. This is much better because you can release different versions of the "interactiveTiles" script. Old maps could stick on v1 with the v1 behaviour, and new map could adopt "interactiveTiles v2" (maybe it modifies the way animations are looped, or adds the possibility to play a sound when a map is walked on?)

We do need some help regarding evolving the scripting API to be powerful enough to do this though ;) . And parts of your PR could be reused for the `WA.setTile` method implementation.

So I hate having to say "no" (especially given the amount of work you put in this), but I believe we need to evolve the scripting API and reimplement this through the scripting API. That will allow us to keep a small core and to add many features in a more maintainable way.

Does it make sense? @gparant @Kharhamel @tabascoeye what do you think?

By the way, we plan to merge your PR about companions (#870) in the coming weeks.

**Comment by tabascoeye** [comment]
Loading unknown JavaScript referenced by a map from an unknown source (i.e. walking over exitUrl) is still giving me headaches in general.
But I understand this is the most probable way to have interactivity built into maps so creators can integrate those without needing to change WA source.

I haven't made up my mind yet.
This is a pretty complete PR which is easy to document and explain to people. But I would understand turning it down.

**Comment by joberthel** [comment]
Im totally fine, if you don't want to merge this pull request. I integrated it in my map and just wanted to share it with you and the community. In general I would prefer if you could set up simple interactions in the map editor and don't have to add external javascript to the map, because many people don't know how to code.

Here is a short video containing some interactions (opening door, fridge, ...):
https://user-images.githubusercontent.com/34104366/114285563-7d9a5d00-9a58-11eb-96a2-40ee86113212.mp4

**Comment by mhupfauer** [comment]
I think this feature is pretty solid and improves the user experience  of WorkAdventure tremendously.
As @joberthel mentioned, this could be used for doors, chairs, coffee machine, vending machine, .... which would be very nice.

I can't tell how much this could "hurt" future changes without breaking maps but I think I'd be absolutely worthwhile.

**Comment by makefu** [comment]
any chance to get this merged?

**Comment by nolway** [comment]
Can be done with the scripting api an areas.

**Pull request closed without merging**
