### PR TITLE
Limit bandwidth for video and screenshare

### PR DESCRIPTION
**Pull request by fcecagno**
Add two new environment variables, `PEER_VIDEO_MAX_BANDWIDTH_KBITS_PS` and `PEER_SCREENSHARE_MAX_BANDWIDTH_KBITS_PS`, in order to limit bandwidth used by the P2P connection in the bubble. Leaving video and screenshare unlimited is problematic because it might take a lot of bandwidth and processing power, which leads to poor quality/experience.
We've been testing very successfully 600 kbps for video and 1000 kbps for screenshare.

### CODE REVIEW

**Comment by zobadaniel** [comment]
Please integrate these changes! I`'m seeing heavy bandwidth utilization without this feature, which is hampering usage for some  (up to 10 MBit/s for a small video - just too much) because they "steal" bandwidth for others! I have integrated this patch with some minor adaptations to an even more recent state of the repo (develop branch) in my environment, and it still works.

**Comment by fcecagno** [comment]
Hi @gparant and @moufmouf , would you consider integrating this in the upcoming minor releases of 1.15? I'd be glad to re-submit it as a clean PR against develop.

@zobadaniel would you like to share the adaptations you did in your fork related to this PR?

**Comment by zobadaniel** [comment]
You can find my changes here:

https://github.com/ZalozbaDev/workadventure/commits/v1.15.6_bwlimit 

I cherry-picked your commits and resolved conflicts (in case there were any), so you should still recognize your work easily:

https://github.com/ZalozbaDev/workadventure/commit/b2544e98f75c9a6a05009061af8ac805481a4382 

https://github.com/ZalozbaDev/workadventure/commit/dcd5399494fe0f57e98d64ad5e277385b94de596 

https://github.com/ZalozbaDev/workadventure/commit/5490e2fcda11188cc961710f80896d66ec91b9e8

https://github.com/ZalozbaDev/workadventure/commit/6138dc608f588caeaf6f57eecc10652e05d0a24e

https://github.com/ZalozbaDev/workadventure/commit/1447fc0f396e20df93bb9fdf1dfbc13a0885a453

https://github.com/ZalozbaDev/workadventure/commit/a89dbf32edadb60b6f3a7473a386c37fc0a49545

I have not checked whether the tests still work. I just saw that most of the time, the limit works as expected, and thus the low-bandwidth peers were working fine, and the high-bandwidth-peers weren't over-using bandwidth (I saw 10 MBit/s without this patch, and this is just too much for a video chat).

**Comment by moufmouf** [comment]
Hey @fcecagno and @zobadaniel ,

Sorry for letting this fall behind.

I'm definitely interested in this PR, but before merging it, I'd like to have a setting available in the configuration panel for the customer to be able to configure this bandwidth himself.
Basically, a small drop down with small / medium / high quality would be great.

**Comment by zobadaniel** [comment]
That's probably similar to how Jitsi does things. But what annoyed me with Jitsi back then, is that if it is a user setting only, the server preference could not be preconfigured.

So if you make it a user setting, then please add an option to define the preference of the instance. For instance if I know I will connect to many low-bandwidth users, I'd select the lowest option as default. Other instances might want highest bandwidth.

**Comment by fcecagno** [comment]
@zobadaniel agreed, I believe specifying a baseline is more important than give granular configuration on media quality.
Just noticed that #1453 implements a configuration in the menu, but it's been there for a while.
This patch allows us to use the bubble with up to 7 people without running out of resources for everyone.

**Comment by fcecagno** [comment]
Closing in favor of #3381

**Pull request closed without merging**
